### ISSUE TITLE
It takes 5 seconds for the server to realize a client has closed

### ISSUE THREAD

**Issue by tadej** [coherence/replication-server#129]
- Make timeout configurable as parameter 
- Send disconnect msg on graceful quit on client

**Comment by rpadrela** [comment]
--disconnect-timeout argument was added to the replication-server and a disconnect-request message was added to the client and server. The Connector class automatically sends the message (called from Dispose()). A Disconnect() was added to the NetworkSystem that the client can make use of if needed.
