### ISSUE TITLE
Multithreading issues in replication server: investigate & resolve/ focus on critical crash issue in this task

### ISSUE THREAD

**Issue by tadej** [coherence/replication-server#154]
Estimate: 4 days. Sandeep leading the way with Mathias and Ricardo helping out.

**Comment by rpadrela** [comment]
@gamedolphin , any pointers please? :D

**Comment by rpadrela** [comment]
@gamedolphin seems to now have a pretty good understanding of where the problem is coming from and is currently working on a solution. I'll be moving on to something else. Still interested in this so will keep an eye on it. :)
