### ISSUE TITLE
Replication server crash (panic)

### ISSUE THREAD

**Issue by tadej** [coherence/replication-server#159]
Cary reported this bug in #coder and it seems to be a race condition, probably related to: https://github.com/coherence/replication-server/issues/154

"Open 4 instances of the space war and hold down space for a couple seconds on each in succession creating a whole lot of traffic and you get a crash in the replication server."

**Comment by tadej** [comment]
Reproduce:

Open 4 instances of the space war and hold down space for a couple seconds on each in succession creating a whole lot of traffic and you get a crash in the replication server.

![image](https://user-images.githubusercontent.com/96423/93986910-3338e380-fd87-11ea-8668-18436c6d03bb.png)

![image](https://user-images.githubusercontent.com/96423/93986929-37fd9780-fd87-11ea-99ad-76c0fc9ef35b.png)

![image](https://user-images.githubusercontent.com/96423/93986938-3c29b500-fd87-11ea-96d3-a81e312b5b97.png)

Possibly being addressed with issue
https://github.com/coherence/replication-server/issues/154

**Comment by rpadrela** [comment]
@gamedolphin shall this issue be marked as done?

**Comment by tadej** [comment]
According to @gamedolphin, this is possibly fixed. 
TODO: retest
