### ISSUE TITLE
Server logs infinite "problem with packet" after client pauses and resumes.

### ISSUE THREAD

**Issue by kingstone426** [coherence/replication-server#166]
The first byte of the brisk packet header denotes the packet mode, and the only allowed values are 1 or 2. For some reason, we read the value 5 off the incoming bitstream.
https://github.com/piot/brisk-protocol-go/blob/master/docs/protocol.md

Regardless of client-side behaviour, the server should respond in a meaningful way with proper error messages that hint to the cause of the problem. We should investigate exactly why the server gives this warning, and improve its behaviour so it:

- [x] Doesn't generate infinite warnings (disconnect client if it keeps sending invalid packet data)
- [ ] Log comprehensive error message, explaining the cause of the packet error, received data vs expected data, and possibly a stack trace.

This problem will not occur since fixing this client-side bug: https://github.com/coherence/replication-client-unity/issues/132

In order to reproduce this problem: 

- checkout: [feat: network auto-reconnect disabled by default #131](https://github.com/coherence/replication-client-unity/pull/131)
- connect to server
- pause unity editor
- wait for server to drop connection
- unpause unity editor

UPDATE: This is a client-side bug. Running the client with log mode trace, it is clear the packet does indeed send a 5 mode.

**Comment by eriksvedang** [comment]
https://github.com/coherence/brisk-protocol-go/pull/9 solves point 1 (avoid infinite warnings)
