### ISSUE TITLE
Replication-server blacklist does not prevent infinite out-of-entity-space errors

### ISSUE THREAD

**Issue by kingstone426** [coherence/replication-server#171]
To reproduce: 
- start the replication-server with parameter --max-entities 15
- connect with sdk-testbed-spacewars and shoot bullets until memory is exceeded
- there will be infinite errors logged to console

**Comment by eriksvedang** [comment]
The first problem I've identified is that the replication server hasn't started using the version of `brisk-protocol-go` with the blacklisting feature, I'll fix that.
