### ISSUE TITLE
Investigate server general bandwidth/performance issues

### ISSUE THREAD

**Issue by tadej** [coherence/replication-server#175]
**Background**

Simulation seems to be suffering from general bandwidth related issues. @cbrisebois has reached the following conclusions:

- The server is sending a hardcoded maximum of 10 entities per update as a way to avoid going over the 1280 octets UDP packet limit. We should pack as many entities as possible up to the packet limit.
- The server is sending only one update per tick update. We should send as many as possible up to a configurable limit.

**Expected**

- Investigate UDP packet fragmentation (currently our max packet size is 1280 octets)
- Investigate how we can implement fixes for the issues encountered so far and open a new issue for each problem

**References**

https://www.pico.net/kb/what-is-the-largest-safe-udp-packet-size-on-the-internet
https://stackoverflow.com/questions/1098897/what-is-the-largest-safe-udp-packet-size-on-the-internet

**Comment by rpadrela** [comment]
Hacks maxComponentCount and maxCount were both removed from the protocol-serializer. https://github.com/coherence/protocol-serializer/issues/83

Server only sending one packet per connection per update was fixed across multiple repositories. https://github.com/coherence/replication-server/issues/194

ECS world serialisation limited to 512 octets was increased to 900 octets. https://github.com/coherence/protocol-serializer/issues/88
