### ISSUE TITLE
SDK a53 + mono starter project. Replication server crashes with 4 clients connecting

### ISSUE THREAD

**Issue by tadej** [coherence/replication-server#200]

**Comment by tadej** [comment]
Trying to mitigate this by reducing the schema in the starter project for now.

The version with the full schema is available here:
https://github.com/coherence/starter-project-unity-mono/tree/6960aee208044e846f87eac0d5d94835fb723442

**Comment by tadej** [comment]
This error should also probably `panic` so we know where it's coming from

**Comment by tadej** [comment]
Even with NO strings and a heavily reduced schema, the replication server crashes with the same error when FIVE clients connect:

```name Schema

namespace Coherence.Generated.FirstProject

component GenericPrefabReference
  prefab Int
  
command GenericCommand
  paramInt1 Int

component GenericFieldInt0
  number Int

component GenericFieldInt1
  number Int
  
component GenericFieldInt2
  number Int
  
component GenericFieldInt3
  number Int

component GenericFieldFloat0
  number Float
  
component GenericFieldFloat1
  number Float

component GenericFieldFloat2
  number Float
  
component GenericFieldFloat3
  number Float

component GenericFieldVector0
  x Float
  y Float
  z Float
  
component GenericFieldVector1
  x Float
  y Float
  z Float

component GenericFieldQuaternion0
  x Float
  y Float
  z Float
  w Float```

**Comment by tadej** [comment]
I just tested with SDK a45 and this problem is **not present** there. The bug was introduced between SDK's a46 and a52.

**Comment by cbrisebois** [comment]
Issue looks like an untrapped error in outbitstream::Close().  Need to change Brook to return an error condition in the case of not enough room to write the accumulated bits on closing a stream.

```
func (s *OutBitStreamImpl) writeAccumulatorToArray() error {
	if s.octetPosition+4 >= uint(len(s.octetArray)) {
		return fmt.Errorf("write accumulator: octet positions outside octet array (%v out of %v)",
			s.octetPosition+4, len(s.octetArray))
	}

	unusedBitCount := 32 - s.bitsInAccumulator
	dwordToWrite := s.ac << unusedBitCount
	binary.BigEndian.PutUint32(s.octetArray[s.octetPosition:s.octetPosition+4], dwordToWrite)

	return nil
}
// Close :
func (s *OutBitStreamImpl) Close() {
	if s.bitsInAccumulator != 0 {
		s.writeAccumulatorToArray()
	}
}
```

Close just ignores any write errors, but it should return the error if there is one so the caller can handle it (probably rewind the entity being written.)
