### ISSUE TITLE
Gets disconnected too often when playing over the internet.

### ISSUE THREAD

**Issue by eriksvedang** [coherence/replication-server#208]

**Comment by rpadrela** [comment]
Could this have anything to do with https://github.com/orgs/coherence/projects/1#card-48995796 ?

**Comment by rpadrela** [comment]
@gamedolphin @kingstone426 @cbrisebois this issue was probably to all the various issues you guys have encountered/fixed recently? We might be able to close this one down now?

**Comment by cbrisebois** [comment]
Not sure it's time to delete this unless we feel like the connections are
super stable.  They aren't yet.  Maybe after Mathias' next changes?
