### ISSUE TITLE
Appears to be a memory leak in the replication server.

### ISSUE THREAD

**Issue by cbrisebois** [coherence/replication-server#215]
It appears to grow faster per connection.

Run 6 headless sdk-testbed-data clients and you'll see the memory on the replication server grow rather quickly.

**Comment by rpadrela** [comment]
I guess the only way for this to happen in a language with garbage collection is if there are circular dependencies.

Example: Object A holding on to object B and object B holding on to object A.

Let me know if you would like me to look into it. (I'm looking for stuff to do :P)

**Comment by cbrisebois** [comment]
yeah, go for it.  I'm punishing the system and looking for things that
break and this is something I noticed that we should not ignore.  I rand
with just a few clients running the sdk-testbed-data app in default
settings and the memory started to climb and never went down.  Though maybe
I didn't wait long enough if the GC is really slow?

**Comment by rpadrela** [comment]
> yeah, go for it. I'm punishing the system and looking for things that break and this is something I noticed that we should not ignore. I rand with just a few clients running the sdk-testbed-data app in default settings and the memory started to climb and never went down. Though maybe I didn't wait long enough if the GC is really slow?
> […](#)

The server seems to recover the allocated memory once the client(s) disconnect, but this is not happening immediately. It took a few minutes (~3mins maybe) for the memory to start dropping to about the same level where it was before client(s) connecting. So, I guess the conclusion is that there isn't a memory leak (at least a very obvious one).
