### ISSUE TITLE
Need to remove dependency to piot/brook-go.

### ISSUE THREAD

**Issue by cbrisebois** [coherence/replication-server#216]
piff, idbf, and packet-descriptor all use piot/brook-go which doesn't have fixes found in coherence go, so we have two forks of the same lib being included in the replication server.  Should only have one.  Could use a replace in the go.mod as a quick fix.

**Comment by cbrisebois** [comment]
![graph](https://user-images.githubusercontent.com/68713879/98742910-102cb800-2364-11eb-88da-42b80256245c.png)

**Comment by ottov1** [comment]
I've imported the two missing repository:
https://github.com/coherence/ibdf-go
https://github.com/coherence/piff-go

**Comment by rpadrela** [comment]
@cbrisebois , piff, idbf, and packet-descriptor no longer use piot/brook-go. Will close task down.
